In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5])
print(type(arr),arr.dtype,arr.size)

arr2 = np.array([1,2,3,4,5,"k"])
print(type(arr2),arr2.dtype)

arr3 = np.array([[1,2,3],[4,5,6]])
print(arr3.shape)

<class 'numpy.ndarray'> int64 5
<class 'numpy.ndarray'> <U21
(2, 3)


In [18]:
arr4 = np.zeros((2,3),dtype = "int64")
print(arr4,arr4.shape)

arr4 = np.ones((2,3),dtype = "int64")
print(arr4,arr4.shape)

arr4 = np.full((2,3),200)
print(arr4,arr4.shape)

arr4 = np.eye((3),dtype = "int64")
print(arr4,arr4.shape)

arr4 = np.arange(1,10,2)
print(arr4,arr4.shape)

arr4 = np.linspace(1,100,4)
print(arr4,arr4.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1]
 [1 1 1]] (2, 3)
[[200 200 200]
 [200 200 200]] (2, 3)
[[1 0 0]
 [0 1 0]
 [0 0 1]] (3, 3)
[1 3 5 7 9] (5,)
[  1.  34.  67. 100.] (4,)


In [24]:
#properties

arr = np.array([1,2,3,45,6,7,8])
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

float_arr = arr.astype(np.float64)
print(float_arr,float_arr.dtype)

(7,)
7
int64
1
[ 1.  2.  3. 45.  6.  7.  8.] float64


In [35]:
#operation on array

a = np.array([[1,2,3],[4,5,6]])
print(a,a.shape)
#dimention change
reshape = a.reshape(3,2)
print(reshape,reshape.shape)

flatened = a.flatten()

print(flatened)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6]


In [13]:
#indexing
arr = np.array([1,2,3,4,5])
a = np.array([[1,2,3],[4,5,6]])

print(arr[0])
print(arr[1])
print(a[0,2])

#fancy indexing

ind = [1,2,3]
print(arr[ind])

#boolean indexing
print(arr[arr > 3])
print(arr[arr % 2 == 0])

1
2
3
[2 3 4]
[4 5]
[2 4]


In [18]:
#slicing
print(arr[1:4])
print(arr[1:])
print(arr[:4])
print(arr[::2])

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 3 5]


In [25]:
#copy vs view
# py_list = [1,2,3,4,5,6]
# sub_list = py_list[1:3]
# print(sub_list)
# sub_list[1] = 500
# print(sub_list)
# print(py_list)

arr = np.array([1,2,3,4,5,6])
sub_arr = arr[1:3]
print(sub_arr)
sub_arr[1] = 500
print(sub_arr)
print(arr)

[2 3]
[  2 500]
[  1   2 500   4   5   6]


In [26]:
#data types

arr = np.array([3+5j])
print(arr,arr.dtype)

[3.+5.j] complex128
