In [6]:
import numpy as np

In [7]:
arr = np.array([1,2,3,4,5])
print(type(arr),arr.dtype,arr.size)

arr2 = np.array([1,2,3,4,5,"k"])
print(type(arr2),arr2.dtype)

arr3 = np.array([[1,2,3],[4,5,6]])
print(arr3.shape)

<class 'numpy.ndarray'> int64 5
<class 'numpy.ndarray'> <U21
(2, 3)


In [18]:
arr4 = np.zeros((2,3),dtype = "int64")
print(arr4,arr4.shape)

arr4 = np.ones((2,3),dtype = "int64")
print(arr4,arr4.shape)

arr4 = np.full((2,3),200)
print(arr4,arr4.shape)

arr4 = np.eye((3),dtype = "int64")
print(arr4,arr4.shape)

arr4 = np.arange(1,10,2)
print(arr4,arr4.shape)

arr4 = np.linspace(1,100,4)
print(arr4,arr4.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1]
 [1 1 1]] (2, 3)
[[200 200 200]
 [200 200 200]] (2, 3)
[[1 0 0]
 [0 1 0]
 [0 0 1]] (3, 3)
[1 3 5 7 9] (5,)
[  1.  34.  67. 100.] (4,)


In [22]:
#properties

arr = np.array([1,2,3,45,6,7,8])
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

float_arr = ar

(7,)
7
int64
1
