In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
print(type(arr),arr.dtype,arr.size)

arr2 = np.array([1,2,3,4,5,"k"])
print(type(arr2),arr2.dtype)

arr3 = np.array([[1,2,3],[4,5,6]])
print(arr3.shape)

<class 'numpy.ndarray'> int64 5
<class 'numpy.ndarray'> <U21
(2, 3)


In [18]:
arr4 = np.zeros((2,3),dtype = "int64")
print(arr4,arr4.shape)

arr4 = np.ones((2,3),dtype = "int64")
print(arr4,arr4.shape)

arr4 = np.full((2,3),200)
print(arr4,arr4.shape)

arr4 = np.eye((3),dtype = "int64")
print(arr4,arr4.shape)

arr4 = np.arange(1,10,2)
print(arr4,arr4.shape)

arr4 = np.linspace(1,100,4)
print(arr4,arr4.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1]
 [1 1 1]] (2, 3)
[[200 200 200]
 [200 200 200]] (2, 3)
[[1 0 0]
 [0 1 0]
 [0 0 1]] (3, 3)
[1 3 5 7 9] (5,)
[  1.  34.  67. 100.] (4,)


In [24]:
#properties

arr = np.array([1,2,3,45,6,7,8])
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

float_arr = arr.astype(np.float64)
print(float_arr,float_arr.dtype)

(7,)
7
int64
1
[ 1.  2.  3. 45.  6.  7.  8.] float64


In [35]:
#operation on array

a = np.array([[1,2,3],[4,5,6]])
print(a,a.shape)
#dimention change
reshape = a.reshape(3,2)
print(reshape,reshape.shape)

flatened = a.flatten()

print(flatened)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6]


In [13]:
#indexing
arr = np.array([1,2,3,4,5])
a = np.array([[1,2,3],[4,5,6]])

print(arr[0])
print(arr[1])
print(a[0,2])

#fancy indexing

ind = [1,2,3]
print(arr[ind])

#boolean indexing
print(arr[arr > 3])
print(arr[arr % 2 == 0])

1
2
3
[2 3 4]
[4 5]
[2 4]


In [18]:
#slicing
print(arr[1:4])
print(arr[1:])
print(arr[:4])
print(arr[::2])

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 3 5]


In [25]:
#copy vs view
# py_list = [1,2,3,4,5,6]
# sub_list = py_list[1:3]
# print(sub_list)
# sub_list[1] = 500
# print(sub_list)
# print(py_list)

arr = np.array([1,2,3,4,5,6])
sub_arr = arr[1:3]
print(sub_arr)
sub_arr[1] = 500
print(sub_arr)
print(arr)

[2 3]
[  2 500]
[  1   2 500   4   5   6]


In [3]:
#data types

arr = np.array([3+5j])
print(arr,arr.dtype)

arr = np.array(["kashinath" , {1,2,3,4},10.10,54])
print(arr,arr.dtype)

[3.+5.j] complex128
['kashinath' {1, 2, 3, 4} 10.1 54] object


In [27]:
# multi-dimentional array

arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)

#sum of array
print(np.sum(arr2D))

#sum of coloum
sum_of_coloum = np.sum(arr2D,axis=0)
print(sum_of_coloum)

#sum of row 
sum_of_row = np.sum(arr2D,axis=1)
print(sum_of_row)

print(arr2D[1:2,1:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[5 6]]


In [35]:
# 3D array

arr3D = np.array([[[1,2],[3,4],[6,7]],[[8,9],[9,10],[11,12]]])
print(arr3D,arr3D.shape)

# indexing arr[axis,row,coloumn]
print(arr3D[1,1,0])

# slicing
print(arr3D[:,0,:]) # first row
print(arr3D[:,:,0]) #first col


[[[ 1  2]
  [ 3  4]
  [ 6  7]]

 [[ 8  9]
  [ 9 10]
  [11 12]]] (2, 3, 2)
9
[[1 2]
 [8 9]]
[[ 1  3  6]
 [ 8  9 11]]


In [52]:
#mathematical functions in numpy
arr = np.array([1,2,3,4,5])
#aggregation 
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))

15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0


In [53]:
#power
print(np.square(arr))
print(np.sqrt(arr))
print(np.power(arr,3))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [54]:
#log
print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [63]:
# rounding
print(np.round(3.4))
print(np.ceil(3.4))
print(np.floor(3.4))
print(np.trunc(3.4))
arr = np.array([1,2,1,4,5,4,-5,-7,8,9])
print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr))

3.0
4.0
3.0
3.0
[-7 -5  1  2  4  5  8  9]
[-7 -5  1  1  2  4  4  5  8  9]
[1 2 1 4 5 4 5 7 8 9]
